name: Run Matchstick tests

on: [push, pull_request]

env:
  NODE_VERSION: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build subgraph.yaml for mainnet
        run: yarn prepare:mainnet

      - name: Run graph codegen
        run: yarn codegen

      - name: Run matchstick tests
        run: yarn test
